/**
 * Parametric TV Remote & Electronic Device Battery Cover Generator
 * Generates both clean, human-editable OpenSCAD code and a ready-to-print binary STL mesh.
 */

const fs = require("fs");
const path = require("path");
const {
  Mesh,
  mergeMeshes,
  createBox,
  createWedge,
  createFilletedPlate
} = require("../csg-engine.js");

function generateBatteryCover(options = {}) {
  // Primary cavity dimensions in mm (supporting standard aliases)
  const rawLength = Number(options.length ?? options.slot_length_mm ?? options.slotLength ?? options.l ?? 62.0);
  const rawWidth = Number(options.width ?? options.slot_width_mm ?? options.slotWidth ?? options.w ?? 33.0);
  const thickness = Number(options.thickness ?? options.slot_depth_mm ?? options.depth ?? options.t ?? 1.6);
  const cornerRadius = Number(options.cornerRadius ?? options.radius ?? options.r ?? 2.5);
  const clearance = Number(options.clearance !== undefined ? options.clearance : (options.tolerance ?? 0.25));

  // Apply clearance fit to outer boundary
  const length = parseFloat((rawLength - (clearance * 2)).toFixed(2));
  const width = parseFloat((rawWidth - (clearance * 2)).toFixed(2));

  // Snap-fit cantilever clip specs
  const clipWidth = Number(options.clipWidth || 12.0);
  const clipLength = Number(options.clipLength || 8.0);
  const hookOverhang = Number(options.hookOverhang || 1.2);

  // Rear retention prongs
  const tabLength = Number(options.tabLength || 3.5);
  const tabWidth = Number(options.tabWidth || 8.0);
  const tabThickness = Math.max(0.8, thickness * 0.7);

  // Ergonomic thumb grip ridges
  const gripRibs = Number(options.gripRibs !== undefined ? options.gripRibs : 5);

  // Output paths
  const outputDir = path.resolve(options.outputDir || path.join(process.cwd(), "output"));
  const baseName = options.filename || `battery_cover_${Math.round(length)}x${Math.round(width)}mm`;

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const scadPath = path.join(outputDir, `${baseName}.scad`);
  const stlPath = path.join(outputDir, `${baseName}.stl`);

  // 1. Generate Parametric OpenSCAD Code
  const scadCode = `// ========================================================
// Parametric TV Remote Battery Cover
// Generated by Gemini CAD MCP
// Model: ${length}mm x ${width}mm (Clearance: ${clearance}mm)
// ========================================================

$fn = 60; // Smooth curve resolution

// --- Primary Cavity Dimensions ---
cavity_length = ${rawLength};    // Nominal cavity length (mm)
cavity_width  = ${rawWidth};     // Nominal cavity width (mm)
clearance     = ${clearance};    // 3D printing tolerance per side (mm)
wall_t        = ${thickness};    // Shell thickness (mm)
corner_r      = ${cornerRadius}; // Corner fillet radius (mm)

// Net outer plate dimensions
plate_l = cavity_length - (clearance * 2);
plate_w = cavity_width - (clearance * 2);

// --- Cantilever Snap Clip ---
clip_w        = ${clipWidth};    // Flex latch arm width (mm)
clip_l        = ${clipLength};   // Flex arm length (mm)
hook_h        = ${hookOverhang}; // Latch barb catch overhang (mm)

// --- Rear Retention Prongs ---
tab_w         = ${tabWidth};     // Alignment tab width (mm)
tab_l         = ${tabLength};    // Alignment tab insertion depth (mm)
tab_t         = ${tabThickness.toFixed(2)}; // Tab thickness (mm)

// --- Ergonomics ---
grip_rib_count = ${gripRibs};    // Thumb-grip tactile ribs

module rounded_plate(l, w, h, r) {
    linear_extrude(height = h) {
        hull() {
            translate([-(w/2 - r), -(l/2 - r)]) circle(r = r);
            translate([ (w/2 - r), -(l/2 - r)]) circle(r = r);
            translate([-(w/2 - r),  (l/2 - r)]) circle(r = r);
            translate([ (w/2 - r),  (l/2 - r)]) circle(r = r);
        }
    }
}

module battery_cover() {
    union() {
        // 1. Main Cover Shell
        rounded_plate(plate_l, plate_w, wall_t, corner_r);

        // 2. Rear Alignment Tabs (inserted into slot first)
        translate([-(plate_w/2 - tab_w/2 - 2), -(plate_l/2 + tab_l), 0])
            cube([tab_w, tab_l + 0.1, tab_t]);
        translate([(plate_w/2 - tab_w/2 - 2) - tab_w, -(plate_l/2 + tab_l), 0])
            cube([tab_w, tab_l + 0.1, tab_t]);

        // 3. Cantilever Snap Latch (front end)
        translate([-clip_w/2, plate_l/2 - clip_l, 0]) {
            // Flexible beam
            cube([clip_w, clip_l, wall_t]);
            // Snap hook / catch wedge
            translate([0, clip_l - 1.2, wall_t])
                rotate([0, 0, 0])
                polyhedron(
                    points = [
                        [0, 0, 0], [clip_w, 0, 0], [clip_w, 1.2, 0], [0, 1.2, 0],
                        [0, 0, hook_h], [clip_w, 0, hook_h]
                    ],
                    faces = [
                        [0, 2, 1], [0, 3, 2], [3, 5, 2], [3, 4, 5],
                        [0, 1, 5], [0, 5, 4], [0, 4, 3], [1, 2, 5]
                    ]
                );
        }

        // 4. Ergonomic Thumb Grip Ribs (exterior textured traction)
        if (grip_rib_count > 0) {
            for (i = [0 : grip_rib_count - 1]) {
                translate([-plate_w * 0.25, (plate_l * 0.1) + (i * 2.5), wall_t])
                    cube([plate_w * 0.5, 1.0, 0.6]);
            }
        }
    }
}

battery_cover();
`;

  // 2. Construct 3D Manifold Geometry
  const meshes = [];

  // Main plate centered at origin on XY
  const mainPlate = createFilletedPlate(width, length, thickness, cornerRadius, 12);
  meshes.push(mainPlate);

  // Rear Retention Tabs (Y negative end)
  const tabY = -length / 2 - tabLength;
  const leftTab = createBox(tabWidth, tabLength + 0.1, tabThickness);
  leftTab.translate(-width / 2 + 2, tabY, 0);
  meshes.push(leftTab);

  const rightTab = createBox(tabWidth, tabLength + 0.1, tabThickness);
  rightTab.translate(width / 2 - tabWidth - 2, tabY, 0);
  meshes.push(rightTab);

  // Front Cantilever Snap-Latch (Y positive end)
  const clipBeam = createBox(clipWidth, clipLength, thickness);
  clipBeam.translate(-clipWidth / 2, length / 2 - clipLength, 0);
  meshes.push(clipBeam);

  // Snap catch wedge on top of beam tip
  const snapHook = createWedge(clipWidth, 1.5, hookOverhang);
  snapHook.translate(-clipWidth / 2, length / 2 - 1.5, thickness);
  meshes.push(snapHook);

  // Ergonomic thumb traction ribs
  if (gripRibs > 0) {
    const ribW = width * 0.5;
    const ribH = 0.5;
    const ribT = 1.0;
    const startY = length * 0.05;
    for (let i = 0; i < gripRibs; i++) {
      const rib = createBox(ribW, ribT, ribH);
      rib.translate(-ribW / 2, startY + (i * 2.5), thickness);
      meshes.push(rib);
    }
  }

  // Merge into watertight manifold mesh
  const finalMesh = mergeMeshes(...meshes);
  const bbox = finalMesh.getBoundingBox();
  const properties = finalMesh.computeProperties();

  // Write files to disk
  fs.writeFileSync(scadPath, scadCode, "utf8");
  const stlBuffer = finalMesh.toBinaryStl(`Gemini CAD - Battery Cover ${length}x${width}mm`);
  fs.writeFileSync(stlPath, stlBuffer);

  return {
    success: true,
    partType: "battery_cover",
    dimensions: {
      nominalCavity: { length: rawLength, width: rawWidth },
      clearanceApplied: clearance,
      printedPlate: { length, width, thickness },
      overallBoundingBoxMm: bbox.size
    },
    files: {
      scadPath,
      stlPath,
      stlSizeBytes: stlBuffer.length
    },
    meshProperties: properties,
    slicerAdvice: {
      recommendedInfill: "15-20% Gyroid or Grid",
      perimeters: 4,
      supportRequired: "None (print flat on bed with textured face up)",
      estimatedPrintTimeMins: Math.max(12, Math.round(properties.volumeCm3 * 8)),
      estimatedFilamentGrams: properties.filamentWeightGrams.pla_20_infill
    },
    scadCode
  };
}

module.exports = {
  generateBatteryCover
};
