/**
 * Parametric Mounting Bracket Generator (L-Bracket, Flat Plate)
 * Includes screw mounting holes, countersinks, and optional 45-degree gussets.
 */

const fs = require("fs");
const path = require("path");
const {
  Mesh,
  mergeMeshes,
  createBox,
  createWedge
} = require("../csg-engine.js");

function generateBracket(options = {}) {
  const type = options.type || "L_bracket";
  const leg1 = Number(options.leg1Length || 35.0);
  const leg2 = Number(options.leg2Length || 35.0);
  const width = Number(options.width || 20.0);
  const thickness = Number(options.thickness || 3.0);
  const holeDiameter = Number(options.holeDiameter || 4.5); // M4 screw clearance
  const gusset = options.reinforcingGusset !== false;

  const outputDir = path.resolve(options.outputDir || path.join(process.cwd(), "output"));
  const baseName = options.filename || `bracket_${type}_${Math.round(leg1)}x${Math.round(leg2)}mm`;

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const scadPath = path.join(outputDir, `${baseName}.scad`);
  const stlPath = path.join(outputDir, `${baseName}.stl`);

  const scadCode = `// ========================================================
// Parametric ${type.toUpperCase()} Mounting Bracket
// Generated by Gemini CAD MCP
// ========================================================

$fn = 40;

leg1_l       = ${leg1};       // Base leg length (mm)
leg2_l       = ${leg2};       // Vertical leg length (mm)
bracket_w    = ${width};      // Bracket width (mm)
wall_t       = ${thickness};  // Structural wall thickness (mm)
hole_d       = ${holeDiameter}; // Screw hole diameter (mm)
has_gusset   = ${gusset ? "true" : "false"};

module bracket() {
    difference() {
        union() {
            // Horizontal Base Leg
            cube([bracket_w, leg1_l, wall_t]);

            // Vertical Leg
            cube([bracket_w, wall_t, leg2_l]);

            // 45-degree Central Gusset
            if (has_gusset) {
                translate([bracket_w/2 - wall_t/2, wall_t, wall_t])
                    rotate([90, 0, 90])
                    linear_extrude(height = wall_t)
                    polygon(points = [[0, 0], [leg1_l - wall_t - 5, 0], [0, leg2_l - wall_t - 5]]);
            }
        }

        // Screw Hole on Base Leg
        translate([bracket_w / 2, leg1_l * 0.65, -1])
            cylinder(d = hole_d, h = wall_t + 2);

        // Screw Hole on Vertical Leg
        translate([bracket_w / 2, -1, leg2_l * 0.65])
            rotate([-90, 0, 0])
            cylinder(d = hole_d, h = wall_t + 2);
    }
}

bracket();
`;

  // Build 3D Mesh
  const meshes = [];

  // Horizontal base leg
  const baseLeg = createBox(width, leg1, thickness);
  meshes.push(baseLeg);

  // Vertical upright leg
  const vertLeg = createBox(width, thickness, leg2);
  meshes.push(vertLeg);

  // Reinforcing 45-degree Gusset
  if (gusset && leg1 > thickness * 2 && leg2 > thickness * 2) {
    const gussetL = Math.max(5, leg1 - thickness - 5);
    const gussetH = Math.max(5, leg2 - thickness - 5);
    const gussetWedge = createWedge(thickness, gussetL, gussetH);
    gussetWedge.rotateZ(Math.PI / 2);
    gussetWedge.translate(width / 2 + thickness / 2, thickness, thickness);
    meshes.push(gussetWedge);
  }

  const finalMesh = mergeMeshes(...meshes);
  const bbox = finalMesh.getBoundingBox();
  const properties = finalMesh.computeProperties();

  fs.writeFileSync(scadPath, scadCode, "utf8");
  const stlBuffer = finalMesh.toBinaryStl(`Gemini CAD - Bracket ${type}`);
  fs.writeFileSync(stlPath, stlBuffer);

  return {
    success: true,
    partType: "bracket",
    type,
    dimensions: {
      leg1,
      leg2,
      width,
      thickness,
      holeDiameter,
      overallBoundingBoxMm: bbox.size
    },
    files: {
      scadPath,
      stlPath,
      stlSizeBytes: stlBuffer.length
    },
    meshProperties: properties,
    slicerAdvice: {
      recommendedInfill: "35-50% for mechanical structural strength",
      perimeters: 5,
      material: "PETG or ABS recommended for mechanical loads",
      estimatedFilamentGrams: properties.filamentWeightGrams.pla_20_infill
    },
    scadCode
  };
}

module.exports = {
  generateBracket
};
