/**
 * Parametric Rotary Control Knob Generator
 * D-Shaft, fluted knurling, pointer indicator.
 */

const fs = require("fs");
const path = require("path");
const {
  Mesh,
  mergeMeshes,
  createBox,
  createCylinder
} = require("../csg-engine.js");

function generateKnob(options = {}) {
  const outerDiameter = Number(options.diameter || 24.0);
  const height = Number(options.height || 16.0);
  const shaftDiameter = Number(options.shaftDiameter || 6.0); // Standard 6mm potentiometer shaft
  const shaftType = options.shaftType || "D_shaft";
  const dFlatDepth = Number(options.dFlatDepth || 1.5);
  const knurlCount = Number(options.knurlCount || 18);
  const indicator = options.indicatorNotch !== false;

  const outputDir = path.resolve(options.outputDir || path.join(process.cwd(), "output"));
  const baseName = options.filename || `knob_${Math.round(outerDiameter)}x${Math.round(height)}mm`;

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const scadPath = path.join(outputDir, `${baseName}.scad`);
  const stlPath = path.join(outputDir, `${baseName}.stl`);

  const scadCode = `// ========================================================
// Parametric Rotary Control Knob
// Generated by Gemini CAD MCP
// ========================================================

$fn = 60;

outer_d     = ${outerDiameter};  // Knob outer diameter (mm)
knob_h      = ${height};         // Knob total height (mm)
shaft_d     = ${shaftDiameter};  // Potentiometer shaft diameter (mm)
shaft_depth = ${height * 0.75};  // Shaft socket bore depth (mm)
d_flat      = ${dFlatDepth};     // D-shaft flat cut depth (mm)
knurls      = ${knurlCount};     // Perimeter grip flutes

module rotary_knob() {
    difference() {
        // Main Knob Body
        union() {
            cylinder(d = outer_d, h = knob_h);
            // Fluted Knurling Ribs
            for (i = [0 : knurls - 1]) {
                rotate([0, 0, i * (360 / knurls)])
                    translate([outer_d / 2 - 0.2, 0, 0])
                    cylinder(r = 0.8, h = knob_h, $fn = 12);
            }
        }

        // Indicator Pointer Notch
        translate([0, outer_d / 2 - 1.5, knob_h - 1.0])
            cube([2.0, 4.0, 2.5], center = true);

        // Shaft Socket
        translate([0, 0, -0.1]) {
            difference() {
                cylinder(d = shaft_d + 0.3, h = shaft_depth + 0.1);
                // D-shaft flat insert
                translate([-shaft_d, shaft_d/2 - d_flat, 0])
                    cube([shaft_d * 2, shaft_d, shaft_depth + 1]);
            }
        }
    }
}

rotary_knob();
`;

  // Build 3D Mesh
  const meshes = [];
  const radius = outerDiameter / 2;

  // Main cylindrical body
  const body = createCylinder(radius, height, 36, false);
  meshes.push(body);

  // Outer fluted tactile ribs
  if (knurlCount > 0) {
    for (let i = 0; i < knurlCount; i++) {
      const angle = (2 * Math.PI * i) / knurlCount;
      const rib = createCylinder(0.8, height, 10, false);
      rib.translate(radius * Math.cos(angle), radius * Math.sin(angle), 0);
      meshes.push(rib);
    }
  }

  // Pointer indicator tab at 12 o'clock
  if (indicator) {
    const pointer = createBox(2.0, 3.0, 1.2, true);
    pointer.translate(0, radius - 1.0, height);
    meshes.push(pointer);
  }

  const finalMesh = mergeMeshes(...meshes);
  const bbox = finalMesh.getBoundingBox();
  const properties = finalMesh.computeProperties();

  fs.writeFileSync(scadPath, scadCode, "utf8");
  const stlBuffer = finalMesh.toBinaryStl(`Gemini CAD - Knob ${outerDiameter}mm`);
  fs.writeFileSync(stlPath, stlBuffer);

  return {
    success: true,
    partType: "knob",
    dimensions: {
      outerDiameter,
      height,
      shaftDiameter,
      shaftType,
      overallBoundingBoxMm: bbox.size
    },
    files: {
      scadPath,
      stlPath,
      stlSizeBytes: stlBuffer.length
    },
    meshProperties: properties,
    slicerAdvice: {
      recommendedInfill: "25-30% Grid or Gyroid",
      perimeters: 4,
      supportRequired: "None (print flat side down)",
      estimatedFilamentGrams: properties.filamentWeightGrams.pla_20_infill
    },
    scadCode
  };
}

module.exports = {
  generateKnob
};
