/**
 * Parametric Standoff, Bushing & Washer Spacer Generator
 * Round or Hexagonal with inner through-hole.
 */

const fs = require("fs");
const path = require("path");
const {
  Mesh,
  mergeMeshes,
  createCylinder
} = require("../csg-engine.js");

function generateSpacer(options = {}) {
  const outerDiameter = Number(options.outerDiameter || 12.0);
  const innerDiameter = Number(options.innerDiameter || 4.5); // Through-hole for M4 screw
  const height = Number(options.height || 10.0);
  const shape = options.shape || "round"; // "round" or "hex"

  const outputDir = path.resolve(options.outputDir || path.join(process.cwd(), "output"));
  const baseName = options.filename || `spacer_${shape}_OD${Math.round(outerDiameter)}_ID${Math.round(innerDiameter)}_H${Math.round(height)}mm`;

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const scadPath = path.join(outputDir, `${baseName}.scad`);
  const stlPath = path.join(outputDir, `${baseName}.stl`);

  const fn = shape === "hex" ? 6 : 48;

  const scadCode = `// ========================================================
// Parametric ${shape.toUpperCase()} Standoff / Bushing Spacer
// Generated by Gemini CAD MCP
// ========================================================

outer_d = ${outerDiameter}; // Outer diameter (or across-flats for hex) (mm)
inner_d = ${innerDiameter}; // Central through-hole diameter (mm)
h       = ${height};        // Standoff length (mm)
$fn     = ${fn};

module spacer() {
    difference() {
        cylinder(d = outer_d, h = h, $fn = ${fn});
        translate([0, 0, -1])
            cylinder(d = inner_d, h = h + 2, $fn = 32);
    }
}

spacer();
`;

  // Construct Hollow Cylinder Mesh
  const rOuter = outerDiameter / 2;
  const rInner = innerDiameter / 2;
  const segments = shape === "hex" ? 6 : 32;

  const vertices = [];
  const faces = [];

  // Bottom outer ring [0 .. segments-1]
  for (let i = 0; i < segments; i++) {
    const a = (2 * Math.PI * i) / segments;
    vertices.push([rOuter * Math.cos(a), rOuter * Math.sin(a), 0]);
  }
  // Bottom inner ring [segments .. 2*segments-1]
  for (let i = 0; i < segments; i++) {
    const a = (2 * Math.PI * i) / segments;
    vertices.push([rInner * Math.cos(a), rInner * Math.sin(a), 0]);
  }
  // Top outer ring [2*segments .. 3*segments-1]
  for (let i = 0; i < segments; i++) {
    const a = (2 * Math.PI * i) / segments;
    vertices.push([rOuter * Math.cos(a), rOuter * Math.sin(a), height]);
  }
  // Top inner ring [3*segments .. 4*segments-1]
  for (let i = 0; i < segments; i++) {
    const a = (2 * Math.PI * i) / segments;
    vertices.push([rInner * Math.cos(a), rInner * Math.sin(a), height]);
  }

  const s = segments;
  for (let i = 0; i < s; i++) {
    const next = (i + 1) % s;
    // Bottom washer face (normal -z)
    faces.push([i, next, next + s]);
    faces.push([i, next + s, i + s]);

    // Top washer face (normal +z)
    faces.push([i + 2 * s, next + 2 * s + s, next + 2 * s]);
    faces.push([i + 2 * s, i + 2 * s + s, next + 2 * s + s]);

    // Outer wall (normal outward)
    faces.push([i, next + 2 * s, next]);
    faces.push([i, i + 2 * s, next + 2 * s]);

    // Inner bore wall (normal inward)
    faces.push([i + s, next + s, next + 3 * s]);
    faces.push([i + s, next + 3 * s, i + 3 * s]);
  }

  const finalMesh = new Mesh(vertices, faces);
  const bbox = finalMesh.getBoundingBox();
  const properties = finalMesh.computeProperties();

  fs.writeFileSync(scadPath, scadCode, "utf8");
  const stlBuffer = finalMesh.toBinaryStl(`Gemini CAD - Spacer ${outerDiameter}x${height}mm`);
  fs.writeFileSync(stlPath, stlBuffer);

  return {
    success: true,
    partType: "spacer",
    shape,
    dimensions: {
      outerDiameter,
      innerDiameter,
      height,
      overallBoundingBoxMm: bbox.size
    },
    files: {
      scadPath,
      stlPath,
      stlSizeBytes: stlBuffer.length
    },
    meshProperties: properties,
    slicerAdvice: {
      recommendedInfill: "100% (Solid for rigid mechanical load transfer)",
      perimeters: 4,
      estimatedFilamentGrams: properties.filamentWeightGrams.pla_100_infill
    },
    scadCode
  };
}

module.exports = {
  generateSpacer
};
